{% set version = "1.5.1" %}

package:
  name: nanocomp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nanocomp/NanoComp-{{ version }}.tar.gz
  sha256: e7f3966b9c3901ac40cd683939724865d236745b7d34321dbb1993e51d8c411c

build:
  entry_points:
    - NanoComp=nanocomp.NanoComp:main
  number: 0
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - pandas
    - numpy
    - nanoplotter >=1.0.0
    - nanoget >=1.4.0
    - nanomath >=0.15.3
    - nanoplot >=1.17.3

test:
  imports:
    - nanocomp

  commands:
    - NanoComp --help

about:
  home: https://github.com/wdecoster/NanoComp
  license: MIT License
  summary: 'Comparing runs of Oxford Nanopore sequencing data and alignments'
  license_family: MIT
