package:
  name: hla-prg-la
  version: 0.0.2

source:
   fn: v0.0.2-kp5.tar.gz
   url: https://github.com/kpalin/HLA-PRG-LA/archive/v0.0.2-kp5.tar.gz
   md5: 451e894d879fdae178be7102f18c4c74

build:
   number: 0

requirements:
   build:
    - boost >=1.59
    - zlib
    - libgcc
    - cmake

   run:
    - boost >=1.59
    - bwa >=0.7.12
    - samtools >=1.3
    - picard

test:
   commands:
     - HLA-PRG-LA --action testBinary

about:
  home: https://github.com/AlexanderDilthey/HLA-PRG-LA
  license: GPL3
  license_file: LICENSE
  summary: Fast HLA type inference from whole-genome data. You still need to download graphs from http://www.well.ox.ac.uk/PRG_MHC_GRCh38_withIMGT.tar.gz as instructed in https://github.com/AlexanderDilthey/HLA-PRG-LA